<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160609114228 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE grades');
        $this->addSql('DROP TABLE log');
        $this->addSql('DROP TABLE master');
        $this->addSql('DROP TABLE students');
        $this->addSql('DROP TABLE userlog');
        $this->addSql('DROP TABLE users');
        $this->addSql('ALTER TABLE amase_log CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE datum datum DATETIME NOT NULL, CHANGE name name VARCHAR(100) NOT NULL, CHANGE ip ip VARCHAR(15) NOT NULL, CHANGE datensatz datensatz INT NOT NULL, CHANGE dtabelle dtabelle VARCHAR(20) NOT NULL, CHANGE dstatus dstatus VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE amase_courses CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE modules_tracks modules_tracks VARCHAR(200) NOT NULL, CHANGE english_description english_description VARCHAR(200) NOT NULL, CHANGE local_description local_description VARCHAR(200) NOT NULL, CHANGE code code VARCHAR(20) NOT NULL, CHANGE ects ects INT NOT NULL, CHANGE university university VARCHAR(20) NOT NULL, CHANGE semester semester INT NOT NULL, CHANGE wer wer VARCHAR(200) NOT NULL, CHANGE datum datum DATETIME NOT NULL, CHANGE author_id author_id TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE amase_countries CHANGE code code VARCHAR(2) NOT NULL, CHANGE en en VARCHAR(50) NOT NULL, CHANGE de de VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE amase_students CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE nachname nachname VARCHAR(150) NOT NULL, CHANGE vorname vorname VARCHAR(150) NOT NULL, CHANGE gender gender VARCHAR(255) NOT NULL, CHANGE university1 university1 VARCHAR(10) NOT NULL, CHANGE matrikel1 matrikel1 VARCHAR(20) NOT NULL, CHANGE university2 university2 VARCHAR(10) NOT NULL, CHANGE matrikel2 matrikel2 VARCHAR(20) NOT NULL, CHANGE universitymaster universitymaster VARCHAR(20) NOT NULL, CHANGE start_semester start_semester VARCHAR(20) NOT NULL, CHANGE study_semester study_semester VARCHAR(255) NOT NULL, CHANGE complete complete VARCHAR(6) NOT NULL, CHANGE birth_date birth_date DATE NOT NULL, CHANGE birth_place birth_place VARCHAR(100) NOT NULL, CHANGE country_birth country_birth VARCHAR(100) NOT NULL, CHANGE geburtsort geburtsort VARCHAR(100) NOT NULL, CHANGE geburtsland geburtsland VARCHAR(100) NOT NULL, CHANGE nationality nationality VARCHAR(100) NOT NULL, CHANGE email email VARCHAR(50) NOT NULL, CHANGE wer wer VARCHAR(100) NOT NULL, CHANGE author_id author_id INT NOT NULL, CHANGE datum datum DATETIME NOT NULL');
        $this->addSql('ALTER TABLE amase_laender CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE land land VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE amase_grades CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(60) NOT NULL, CHANGE university university VARCHAR(20) NOT NULL, CHANGE course_id course_id INT NOT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE student_id student_id VARCHAR(15) NOT NULL, CHANGE modul modul VARCHAR(100) NOT NULL, CHANGE local_grade local_grade VARCHAR(12) NOT NULL, CHANGE ects_grade ects_grade VARCHAR(12) NOT NULL, CHANGE credits credits NUMERIC(3, 1) NOT NULL, CHANGE try try VARCHAR(11) NOT NULL, CHANGE wer wer VARCHAR(40) NOT NULL, CHANGE datum datum DATETIME NOT NULL, CHANGE author_id author_id SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE amase_statistics CHANGE lastname lastname VARCHAR(100) NOT NULL, CHANGE firstname firstname VARCHAR(100) NOT NULL, CHANGE university university TINYINT(1) NOT NULL, CHANGE average_grade average_grade NUMERIC(10, 2) NOT NULL, CHANGE choice choice TINYINT(1) NOT NULL, CHANGE student_id student_id INT NOT NULL');
        $this->addSql('ALTER TABLE amase_master CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(250) NOT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE student_id student_id VARCHAR(15) NOT NULL, CHANGE university university VARCHAR(40) NOT NULL, CHANGE examiner1 examiner1 VARCHAR(60) NOT NULL, CHANGE examiner2 examiner2 VARCHAR(60) NOT NULL, CHANGE examiner_grade1 examiner_grade1 VARCHAR(12) NOT NULL, CHANGE examiner_grade2 examiner_grade2 VARCHAR(12) NOT NULL, CHANGE local_grade_master local_grade_master VARCHAR(6) NOT NULL, CHANGE ects_grade ects_grade VARCHAR(7) NOT NULL, CHANGE credits_master credits_master NUMERIC(3, 1) NOT NULL, CHANGE try try VARCHAR(11) NOT NULL, CHANGE wer wer VARCHAR(40) NOT NULL, CHANGE datum datum DATETIME NOT NULL, CHANGE author_id author_id SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE amase_users CHANGE fullname fullname VARCHAR(50) NOT NULL, CHANGE firma firma VARCHAR(50) NOT NULL, CHANGE email email VARCHAR(40) NOT NULL, CHANGE passwort passwort VARCHAR(32) NOT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE wer wer VARCHAR(100) NOT NULL, CHANGE author_id author_id INT NOT NULL, CHANGE datum datum DATETIME NOT NULL');
        $this->addSql('ALTER TABLE amase_userlog CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE datum datum DATETIME NOT NULL, CHANGE name name VARCHAR(100) NOT NULL, CHANGE uip uip VARCHAR(15) NOT NULL, CHANGE ustatus ustatus VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE amase_countrylist CHANGE ccode ccode VARCHAR(2) NOT NULL, CHANGE name name VARCHAR(200) NOT NULL');
        $this->addSql('ALTER TABLE amase_countries_en CHANGE ccode ccode VARCHAR(2) NOT NULL, CHANGE country country VARCHAR(200) NOT NULL');
        $this->addSql('ALTER TABLE amase_nationalities CHANGE nationality nationality VARCHAR(100) NOT NULL');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE grades (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(60) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, status VARCHAR(255) DEFAULT \'grade\' NOT NULL COLLATE utf8_unicode_ci, student_id VARCHAR(15) DEFAULT \'0\' NOT NULL COLLATE utf8_unicode_ci, coursename TEXT NOT NULL COLLATE utf8_unicode_ci, ex_date DATE DEFAULT NULL, modul VARCHAR(30) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, university VARCHAR(40) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, local_grade VARCHAR(12) DEFAULT \'none\' NOT NULL COLLATE utf8_unicode_ci, ects_grade VARCHAR(7) DEFAULT \'not set\' NOT NULL COLLATE utf8_unicode_ci, credits NUMERIC(2, 1) DEFAULT \'0.0\' NOT NULL, try VARCHAR(11) DEFAULT \'1st attempt\' NOT NULL COLLATE utf8_unicode_ci, wer VARCHAR(40) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, datum DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, author_id SMALLINT DEFAULT 0 NOT NULL, FULLTEXT INDEX coursename (coursename), FULLTEXT INDEX name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE log (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, datum DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, name VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, ip VARCHAR(15) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, datensatz INT DEFAULT 0 NOT NULL, dtabelle VARCHAR(20) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, dstatus VARCHAR(255) DEFAULT \'change\' NOT NULL COLLATE utf8_unicode_ci, ddiff TEXT NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE master (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(250) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, status VARCHAR(255) DEFAULT \'open\' NOT NULL COLLATE utf8_unicode_ci, student_id VARCHAR(15) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, projectname TEXT NOT NULL COLLATE utf8_unicode_ci, ex_date DATE DEFAULT NULL, university VARCHAR(40) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, examiner1 VARCHAR(60) DEFAULT \'none\' NOT NULL COLLATE utf8_unicode_ci, examiner2 VARCHAR(60) DEFAULT \'none\' NOT NULL COLLATE utf8_unicode_ci, examiner_grade1 VARCHAR(12) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, examiner_grade2 VARCHAR(12) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, local_grade VARCHAR(6) DEFAULT \'none\' NOT NULL COLLATE utf8_unicode_ci, ects_grade VARCHAR(7) DEFAULT \'not set\' NOT NULL COLLATE utf8_unicode_ci, credits NUMERIC(2, 1) DEFAULT \'0.0\' NOT NULL, try VARCHAR(11) DEFAULT \'1\' NOT NULL COLLATE utf8_unicode_ci, wer VARCHAR(40) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, datum DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, author_id SMALLINT DEFAULT 0 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE students (id INT UNSIGNED AUTO_INCREMENT NOT NULL, nachname VARCHAR(150) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, vorname VARCHAR(150) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, gender VARCHAR(255) DEFAULT \'male\' NOT NULL COLLATE utf8_unicode_ci, university1 VARCHAR(10) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, matrikel1 VARCHAR(20) DEFAULT \'0\' NOT NULL COLLATE utf8_unicode_ci, university2 VARCHAR(10) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, matrikel2 VARCHAR(20) DEFAULT \'0\' NOT NULL COLLATE utf8_unicode_ci, start_semester VARCHAR(6) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, study_semester VARCHAR(255) DEFAULT \'not set\' NOT NULL COLLATE utf8_unicode_ci, birth_date DATE DEFAULT \'0000-00-00\' NOT NULL, birth_place VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, nationality VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, email VARCHAR(50) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, wer VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, author_id INT UNSIGNED DEFAULT 0 NOT NULL, datum DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, FULLTEXT INDEX vorname (nachname), FULLTEXT INDEX nachname (vorname), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE userlog (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, datum DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, name VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, uip VARCHAR(15) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, ustatus VARCHAR(255) DEFAULT \'login\' NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, fullname VARCHAR(50) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, firma VARCHAR(50) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, email VARCHAR(40) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, passwort VARCHAR(32) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, status VARCHAR(255) DEFAULT \'user\' NOT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX email (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE amase_countries CHANGE code code CHAR(2) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE en en VARCHAR(50) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE de de VARCHAR(50) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE amase_countries_en CHANGE ccode ccode CHAR(2) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE country country VARCHAR(200) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE amase_countrylist CHANGE ccode ccode CHAR(2) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE name name VARCHAR(200) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE amase_courses CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE modules_tracks modules_tracks VARCHAR(200) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE english_description english_description VARCHAR(200) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE local_description local_description VARCHAR(200) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE code code VARCHAR(20) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE ects ects INT DEFAULT 0 NOT NULL, CHANGE university university VARCHAR(20) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE semester semester INT DEFAULT 0 NOT NULL, CHANGE wer wer VARCHAR(200) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE datum datum DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE author_id author_id TINYINT(1) DEFAULT \'0\' NOT NULL');
        $this->addSql('ALTER TABLE amase_grades CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(60) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE university university VARCHAR(20) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE course_id course_id INT DEFAULT 0 NOT NULL, CHANGE status status VARCHAR(255) DEFAULT \'grade\' NOT NULL COLLATE utf8_unicode_ci, CHANGE student_id student_id VARCHAR(15) DEFAULT \'0\' NOT NULL COLLATE utf8_unicode_ci, CHANGE modul modul VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE local_grade local_grade VARCHAR(12) DEFAULT \'none\' NOT NULL COLLATE utf8_unicode_ci, CHANGE ects_grade ects_grade VARCHAR(12) DEFAULT \'0.0\' NOT NULL COLLATE utf8_unicode_ci, CHANGE credits credits NUMERIC(3, 1) DEFAULT \'0.0\' NOT NULL, CHANGE try try VARCHAR(11) DEFAULT \'1st attempt\' NOT NULL COLLATE utf8_unicode_ci, CHANGE wer wer VARCHAR(40) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE datum datum DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE author_id author_id SMALLINT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE amase_laender CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE land land VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE amase_log CHANGE id id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE datum datum DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE name name VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE ip ip VARCHAR(15) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE datensatz datensatz INT DEFAULT 0 NOT NULL, CHANGE dtabelle dtabelle VARCHAR(20) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE dstatus dstatus VARCHAR(255) DEFAULT \'change\' NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE amase_master CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(250) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE status status VARCHAR(255) DEFAULT \'open\' NOT NULL COLLATE utf8_unicode_ci, CHANGE student_id student_id VARCHAR(15) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE university university VARCHAR(40) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE examiner1 examiner1 VARCHAR(60) DEFAULT \'none\' NOT NULL COLLATE utf8_unicode_ci, CHANGE examiner2 examiner2 VARCHAR(60) DEFAULT \'none\' NOT NULL COLLATE utf8_unicode_ci, CHANGE examiner_grade1 examiner_grade1 VARCHAR(12) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE examiner_grade2 examiner_grade2 VARCHAR(12) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE local_grade_master local_grade_master VARCHAR(6) DEFAULT \'none\' NOT NULL COLLATE utf8_unicode_ci, CHANGE ects_grade ects_grade VARCHAR(7) DEFAULT \'not set\' NOT NULL COLLATE utf8_unicode_ci, CHANGE credits_master credits_master NUMERIC(3, 1) DEFAULT \'0.0\' NOT NULL, CHANGE try try VARCHAR(11) DEFAULT \'1\' NOT NULL COLLATE utf8_unicode_ci, CHANGE wer wer VARCHAR(40) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE datum datum DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE author_id author_id SMALLINT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE amase_nationalities CHANGE nationality nationality VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE amase_statistics CHANGE lastname lastname VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE firstname firstname VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE university university TINYINT(1) DEFAULT \'0\' NOT NULL, CHANGE average_grade average_grade NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, CHANGE choice choice TINYINT(1) DEFAULT \'0\' NOT NULL, CHANGE student_id student_id INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE amase_students CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE nachname nachname VARCHAR(150) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE vorname vorname VARCHAR(150) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE gender gender VARCHAR(255) DEFAULT \'male\' NOT NULL COLLATE utf8_unicode_ci, CHANGE university1 university1 VARCHAR(10) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE matrikel1 matrikel1 VARCHAR(20) DEFAULT \'0\' NOT NULL COLLATE utf8_unicode_ci, CHANGE university2 university2 VARCHAR(10) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE matrikel2 matrikel2 VARCHAR(20) DEFAULT \'0\' NOT NULL COLLATE utf8_unicode_ci, CHANGE universitymaster universitymaster VARCHAR(20) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE start_semester start_semester VARCHAR(20) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE study_semester study_semester VARCHAR(255) DEFAULT \'not set\' NOT NULL COLLATE utf8_unicode_ci, CHANGE complete complete VARCHAR(6) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE birth_date birth_date DATE DEFAULT \'0000-00-00\' NOT NULL, CHANGE birth_place birth_place VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE country_birth country_birth VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE geburtsort geburtsort VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE geburtsland geburtsland VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE nationality nationality VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE email email VARCHAR(50) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE wer wer VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE author_id author_id INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE datum datum DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE amase_userlog CHANGE id id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE datum datum DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE name name VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE uip uip VARCHAR(15) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE ustatus ustatus VARCHAR(255) DEFAULT \'login\' NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE amase_users CHANGE fullname fullname VARCHAR(50) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE firma firma VARCHAR(50) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE email email VARCHAR(40) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE passwort passwort VARCHAR(32) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE status status VARCHAR(255) DEFAULT \'user\' NOT NULL COLLATE utf8_unicode_ci, CHANGE wer wer VARCHAR(100) DEFAULT \'\' NOT NULL COLLATE utf8_unicode_ci, CHANGE author_id author_id INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE datum datum DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
    }
}
